name: CMake Build (Debug)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - if: matrix.os == 'ubuntu-latest'
        name: Install X.Org
        run: sudo apt install xorg-dev
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ env.BUILD_TYPE }}
      - if: matrix.os == 'windows-latest'
        name: Upload executable (Windows)
        uses: actions/upload-artifact@v2
        with:
          name: Dripleaf-debug-${{ matrix.os }}
          path: |
            build/${{ env.BUILD_TYPE }}/*.exe
      - if: matrix.os == 'ubuntu-latest'
        name: Upload executable (Linux)
        uses: actions/upload-artifact@v2
        with:
          name: Dripleaf-debug-${{ matrix.os }}
          path: |
            build/Dripleaf*